export const UIActionType = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  DISPLAY_NOTIFICATION_DRAWER: 'DISPLAY_NOTIFICATION_DRAWER',
  HIDE_NOTIFICATION_DRAWER: 'HIDE_NOTIFICATION_DRAWER',
}
